name: hlint

on:
  pull_request:
  push:

jobs:
  style:
    name: hlint
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - uses: haskell/actions/hlint-setup@v2
        name: Set up HLint
        with:
          version: "3.4"

      - name: hlint
        run: |
          set -ex
          hlint src/
          hlint src/ --cpp-define=WINDOWS=1
          hlint test/ --cpp-simple
